### ISSUE TITLE
Description and previews

### ISSUE THREAD

**Issue by RedRain77** [bhrevol/dlsite-async#104]
Would it be possible to also get the description and preview images of a work?
Thank you for the API :)

**Comment by bhrevol** [comment]
The preview images I can do.

I'm not sure what the best way to handle the detailed descriptions would be since they are essentially an entire webpage and can also have embedded images. I'll have to look and see if there's an easy way to scrape the shorter descriptions you get on the main dlsite index and search pages.

**Comment by bhrevol** [comment]
This is released on v0.3.0

**Comment by RedRain77** [comment]
> This is released in v0.3.0

your amazing :)
Thank you so much!
